services:
  hbf:
    image: mohitsharma44/hbf:latest
    environment:
      - HBF_IFACE=${HBF_IFACE:-docker0}
      - HBF_TIME_THRESHOLD=${HBF_TIME_THRESHOLD:-1}
      - HBF_MAX_PORTS=${HBF_MAX_PORTS:-5}
      - HBF_TIMEOUT_SECONDS=${HBF_TIMEOUT_SECONDS:-300}
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    volumes:
      # https://github.com/iovisor/bcc/issues/1875#issuecomment-490557082
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /sys/fs/bpf:/sys/fs/bpf
      - /lib/modules:/lib/modules:ro
      - /usr/src:/usr/src:ro
      - /usr/lib:/usr/lib
      - /sys/kernel/debug:/sys/kernel/debug:ro
    network_mode: "host"
    privileged: true
    command:
      - "start"
